Попап выбора города
aaccent/everest-front pull request #117
Opened 2024-10-07 14:52 UTC by regina-ms

2024-10-14 14:34 UTC, foxhable requested changes

2024-10-14 14:34 UTC, foxhable commented on src/components/GeoPosition.tsx
> +  return showNotification()
Функция лишняя, можно упростить до

```suggestion
  if (cookies().has('city')) return null
  
  return <GeoPositionNotification cityByIp={cityByIp} />
```

2024-10-14 14:34 UTC, foxhable commented on src/features/utility/getCityByIp.ts
> +const DADATA_URL = 'http://suggestions.dadata.ru/suggestions/api/4_1/rs/iplocate/address?language=ru&ip='
Разве http? Не https?

2024-10-14 14:34 UTC, foxhable commented on src/features/utility/getCityByIp.ts
> +const DADATA_TOKEN = 'b087714991bd2f588921e63e693dc999bb4f6710'
Перемести в .env. Это наш токен, после сдачи проекта он может поменяться и проще будет менять через env

2024-10-14 14:34 UTC, foxhable commented on src/features/utility/getCityByIp.ts
> +export async function getCityByIp(): Promise<string> {
Логичнее будет закинуть в `globals/api/methods/`

2024-10-14 14:34 UTC, foxhable commented on src/globals/CityContext.tsx
> +    }
```suggestion
    if (!cookie) return
    
    getLocation().then((res) => {
      const city = res.cities.find((city) => cookie.value.includes(city.name))
      setCurrentCity(city || null)
    })
```

2024-10-14 14:34 UTC, foxhable commented on src/globals/CityContext.tsx
> +    setCookie('city', city.name)
Импортируй и используй константу `COOKIES`:
```ts
    setCookie(COOKIES.CITY, city.name)
```

2024-10-14 14:34 UTC, foxhable commented on src/components/GeoPosition.tsx
> +    if (!cookies().has('city')) {
Используй константу `COOKIES`:

```ts
    if (!cookies().has(COOKIES.CITY)) {
```

2024-10-14 14:34 UTC, foxhable commented on src/globals/CityContext.tsx
> +import { getLocation } from '@/globals/api/methods/getLocation'
Поменяй экспорты и импорты чтобы стало:
```ts
import { getLocation } from '@/globals/api'
```

Можно создать папку `api/geo` и поместить туда эту функцию и функцию от дадаты `getCityByIp()` в разные файлы

2024-10-14 14:34 UTC, foxhable commented on src/ui/inputs/Checkbox.tsx
> +  return changeMobileView ? (
Легче для чтения будет поместить `changeMobileView` в `if` блок:

```tsx
if (changeMobileView) {
  return <></>
}

return <></>
```

2024-10-14 14:34 UTC, foxhable commented on src/ui/popups/GeoPopup/GeoPopup.tsx
> +    getLocation().then((res) => setLocation(res))
```suggestion
    getLocation().then(setLocation)
```

2024-10-14 14:34 UTC, foxhable commented on src/ui/popups/GeoPopup/GeoPopup.tsx
> +  const onCheckboxClick = () => {
Аж трясет

```suggestion
  }, [])
  
  const onCheckboxClick = () => {
```

2024-10-14 14:34 UTC, foxhable commented on src/ui/popups/GeoPopup/GeoPopup.tsx
> +    return location?.cities.map((c) => {
Переименуй `c` в `city`

2024-10-14 15:00 UTC, regina-ms commented on src/features/utility/getCityByIp.ts
> +const DADATA_URL = 'http://suggestions.dadata.ru/suggestions/api/4_1/rs/iplocate/address?language=ru&ip='
![image](https://github.com/user-attachments/assets/82f71ee2-c1a0-4b64-8f81-c59b500eff07)
В доке http

2024-10-15 07:54 UTC, foxhable approved these changes

2024-10-15 07:54 UTC, merged