Пагинация списка ЖК
aaccent/everest-front pull request #142
Opened 2024-10-21 09:17 UTC by regina-ms

2024-10-23 06:54 UTC, foxhable requested changes

2024-10-23 06:54 UTC, foxhable commented on src/globals/paginationConst.ts
> +}
Я тоже создал подобный файл - `globals/pagination.ts`, оставь его, а `paginationConst.ts` удали

2024-10-23 06:54 UTC, foxhable commented on src/types/RequestProps.ts
> +export type GeneralRequestParams = SortRequest & FilterRequest & PaginationRequest & LocationRequest
Мысли читаешь, тоже хотел перенести потом эти типы в отдельный файл и разделить по типам

2024-10-23 06:54 UTC, foxhable commented on src/globals/api/methods/catalog/getComplexes.ts
> +export async function getComplexes({ ...options }: Props = {}): Promise<ComplexesCategory> {
Убери лишнюю деструктуризацию:
```ts
async function getComplexes(options: Props = {});
```

2024-10-23 06:54 UTC, foxhable commented on src/globals/api/methods/catalog/getCategory.ts
> +  if (subcategory === 'complexes') return res.data
Из-за этого где-то ошибка возникала?

2024-10-23 07:22 UTC, regina-ms commented on src/globals/api/methods/catalog/getCategory.ts
> +  if (subcategory === 'complexes') return res.data
нет, я пыталась соединить методы `getCategory` и `getComplexes` и забыла убрать строку

2024-10-28 10:21 UTC, foxhable approved these changes

2024-10-28 10:21 UTC, merged