feat: Services section
aaccent/everest-front pull request #17
Opened 2024-07-12 13:30 UTC by regina-ms

2024-07-16 14:34 UTC, foxhable requested changes

2024-07-16 14:36 UTC, foxhable requested changes

2024-07-16 14:36 UTC, foxhable commented on src/app/page.tsx
>        <UsefulLinks />
Перемести соответственно макету

```suggestion
      <SliderSection type={'newBuildings'} />
      <Services />
      <UsefulLinks />
```

2024-07-16 14:38 UTC, foxhable requested changes

2024-07-16 14:38 UTC, foxhable commented on src/components/Services/Services.tsx
> +      </IsMobile>
Нет необходимости в `IsDesktop` и `IsMobile`. Можно заменить на стили:
1. Меняем вывод `MoreServicesButton` чтобы он оборачивал детей и вставлял под ними кнопку. При нажатии на кнопку меняется класс обертки
```js
function ServicesWrapperWithButton({ servicesLength, className, children }: MoreServicesButtonProps) {
  const [full, setFull] = useState<boolean>(false)

  const onButtonClick = () => {
    setFull((prev) => !prev)
  }
  return (
    <div className={`group/services ${full ? 'active' : ''}`}>
      {children}
      <button
        onClick={onButtonClick}
        className={`text-base-500-reg-100-upper mt-[16px] flex w-full items-center justify-center rounded-[20px] bg-base-100 py-[18px] text-base-600`}
      >
        {full ? 'Свернуть' : `показать ещё ${servicesLength}`}
      </button>
    </div>
  )
}
```

2. Далее используем обертку и (ра)скрываем лишних детей через `nth-child`
```js
async function Services() {
  const services = await getServices()

  return (
    <DecorativeSection className='bg-primary text-base-100 md:pb-[40px]' title='сервисы нашего агентства'>
      <ServicesWrapperWithButton
        servicesLength={services.length - 3}
        className='grid gap-[8px] md:grid-cols-2 md:gap-[24px] [&>*:nth-child(n+4)]:hidden group-[.active]/services:[&>*:nth-child(n+4)]:flex md:[&>*:nth-child(n+4)]:flex'
      >
        {showServices(services)}
      </ServicesWrapperWithButton>
    </DecorativeSection>
  )
}
```

2024-07-16 14:38 UTC, foxhable commented on src/app/page.tsx
>        <UsefulLinks />
Перемести соответственно макету

```suggestion
      <SliderSection type={'newBuildings'} />
      <Services />
      <UsefulLinks />
```

2024-07-16 14:38 UTC, foxhable commented on src/components/Services/Services.tsx
> +export function showServices(services: Service[]) {
Перемести функцию над `Services` для сохранения порядка вызовов.

Почему она экспортируется? Если нет использования извне, то не стоит путать экспортом. Нет нужды в `<>` можно сократить.
```js
function showServices(services: Service[]) {
  return services.map(() => <Link>...</Link>)
}
```

2024-07-26 11:30 UTC, regina-ms commented on src/components/Services/Services.tsx
> +      </IsMobile>
нужна помощь с этим - при нажатии на кнопку список не раскрывается

2024-08-01 10:06 UTC, foxhable submitted a review, later dismissed

2024-08-01 10:20 UTC, foxhable commented on src/components/Services/Services.tsx
> +      </IsMobile>
Забыл обернуть `{children}` в ещё один `div`. В стилях активное состояние проверяется у группы `group/services`, но стили проверки находится в том же списке стилей, где и объявление группы.
То-есть подобное работать не будет:
```jsx
<div className="group hidden group-has-[.active]:block" />
```
А это будет:
```jsx
<div className="group">
  <div className="hidden group-has-[.active]:block" />
</div>
```

2024-08-01 10:23 UTC, merged