feat: complex-page
aaccent/everest-front pull request #19
Opened 2024-07-23 15:08 UTC by regina-ms

## Попытка сделать:  
- Компонент заголовка страницы, куда входит заголовок, хлебные крошки и опционально: кол-во предложений и подкатегории
- Кнопки из будущего фильтра, которые меняют отображение карточек 
- Контекст, из которого приходит вид отображения карточек
- Метод запроса ЖК для главной (есть в доке свагера)

2024-07-24 09:27 UTC, foxhable requested changes

2024-07-24 09:27 UTC, foxhable commented on src/components/Cards/ComplexCard/CardInfo.tsx
> +          <div className='text-header-500'>{props.minPrice ? formatPrice(props.minPrice) : 'нет цены'}</div>
Чтобы не писать везде одно и то же условие с тернарным оператором, лучше дописать `formatPrice()`:
```ts
function formatPrice(price: number | null | undefined) {
  if (!price) return 'нет цены'
  
  // ...
}
```

2024-07-24 09:27 UTC, foxhable commented on src/components/Cards/ComplexCard/CardInfo.tsx
> +            {props.status ? formatStatus(props.status) : 'неизвестно'}
И по подобию с ценой тут. Только вместо условия добавить `default` кейс

2024-07-24 09:27 UTC, foxhable commented on src/components/Slider/SliderSection.tsx
> +  switch (props.type) {
`title` и `data` должны передаваться через параметры. У тебя к концу разработки будет кейсов 10 с таким подходом

2024-07-24 09:27 UTC, foxhable commented on src/page-components/catalog/CatalogContent/CatalogContent.tsx
> +type CatalogContentProps = { list: Complex[] } /** или другие типы карточек*/
`/** или другие типы карточек*/`
Если хотела сказать, что позже добавиться типы карточек Объектов и Новостроек - то так и пиши. Комментарий не должен оставлять вопросов.

Комментарии вида `/** comment */` с дополнительной `*` в начале нужны для документации JSDoc и TSDoc. Обычные `// comment` и `/* comment */` для свободных комментариев. Поэтому если не описываешь документацию, то лучше не оставлять такого вида, т.к. если в проекте будут использовать инструменты для генерации документаций, то подобные комментарии могут попасть в доку

2024-07-24 09:27 UTC, foxhable commented on src/page-components/catalog/CatalogContent/CatalogContent.tsx
> +  return view === 'tile' ? props.list.map((card) => <ComplexCard {...card} key={card.id} />) : <>карточки списком</>
Лучше для читабельности переделать на `if else`

2024-07-24 11:51 UTC, regina-ms commented
- Исправлены пункты в комментариях
- Добавлен вид списка карточек ЖК
- Добавлена кнопка Показать еще в секции с карточками ЖК

2024-07-25 08:29 UTC, foxhable requested changes

2024-07-25 08:29 UTC, foxhable commented on src/components/Cards/Complex/CardInfo.tsx
> +}
Перемести функцию перед её вызовом

2024-07-25 08:29 UTC, foxhable commented on src/components/Cards/Complex/ComplexCard.tsx
> +
Перемести функцию выше - перед её использованием

2024-07-25 08:29 UTC, foxhable commented on src/components/Cards/Complex/ComplexFullCard.tsx
> +        <div
Если ты знаешь, что в иконке будет сто 100% svg, то можно добавить атрибут `unoptimized` и убрать необходимость в атрибутах width и height

2024-07-25 08:29 UTC, foxhable commented on src/page-components/catalog/CatalogContent/CatalogContent.tsx
> +      if (view === 'tile' || matchMedia('max-width: 768px').matches) {
У нас пагинация будет реализована через АПИ. Учти что в будущем это будет переписано и нам не нужно самим делить через splice

2024-07-25 08:29 UTC, foxhable commented on src/page-components/catalog/CatalogContent/CatalogContent.tsx
> +      if (view === 'tile' || matchMedia('max-width: 768px').matches) {
Ещё советую начинать использовать `toSpliced` для того чтобы не менять изначальный объект

2024-07-25 08:29 UTC, foxhable commented on src/page-components/catalog/CatalogPageTitle.tsx
> +        >
У тебя тут было `right-[50%]`. В будущем если понадобится использовать `50%`, `25%` или `33%` - используй преднастроеные в таилвинд `1/2`, `1/4` и `1/3`

2024-07-25 10:08 UTC, foxhable submitted a review, later dismissed

2024-07-25 10:37 UTC, merged