Попап
aaccent/everest-front pull request #22
Opened 2024-07-24 14:29 UTC by regina-ms

##Добавлено
- вызов попапа Связаться с риелтором по кнопке в шапке

2024-07-25 15:06 UTC, regina-ms commented
- createPortal для вызова попапа

2024-08-01 09:54 UTC, foxhable requested changes

2024-08-01 09:54 UTC, foxhable commented on src/components/Popup/Popup.tsx
> +    document.body.style.overflow = 'clip'
1. `clip` тоже самое, что и `hidden`, только позволяет работать `position: sticky`. Значение по по-умолчанию это `auto`.
2. Используй функцию `showScroll()` из `features/scroll`

2024-08-01 09:54 UTC, foxhable commented on src/components/Popup/Popup.tsx
> +  const [popup, setPopup] = useState<E | undefined>()
В сообществе и в самом языке JS принято, что `undefined` - это отсутствие значения вовсе, а `null` - это пустое значение. `undefined` может быть только что созданная переменная без значения. `null` если значение известно и это значение пустое. 

`document.querySelector()` например возвращает `null` если ничего не находит. Лучше сделать значение состояния `null` если не установлен попап

2024-08-01 09:54 UTC, foxhable commented on src/components/Popup/Popup.tsx
> +      {popup ? createPortal(<PopupWrapper />, document.body) : null}
`createPortal` необходим только в случае если Попапы пришлось бы выводить по-виртуальному DOM внутри какого-нибудь компонента. Здесь же нет необходимости в нем, т.к. Провайдер без и с порталом будет выводить `PopupWrapper` в корне `body`

2024-08-01 09:54 UTC, foxhable commented on src/components/Popup/Popup.tsx
> +  return activePopup && <div className='fixed inset-0 z-50 bg-base-600/60'>{activePopup}</div>
Можно сделать красивше
```jsx
  if (!activePopup) return null

  return <div className='fixed inset-0 z-50 bg-base-600/60'>{activePopup}</div>
```

Тогда не будет необходимости в проверке ниже через тернарный оператор:
```jsx
<PopupContext.Provider>
  <PopupWrapper/>
</PopupContext.Provider>
```

2024-08-01 09:54 UTC, foxhable commented on src/components/Popup/Popup.tsx
> +}
С точки зрения типизации сюда можно впихнуть че угодно и оно будет работать без ошибок со стороны типизации. Но может возникнуть ошибка если ты случайно напишешь в виде JSX компонент вместо передачи функции. Для надежности лучше добавить `satisfies`:
```tsx
const popups = {
  callPopup: CallPopup,
  mapPopup: MapPopup,
} satisfies {
  [index: string]: () => React.ReactNode
}
```

2024-08-09 10:35 UTC, foxhable submitted a review, later dismissed

2024-08-09 10:39 UTC, foxhable approved these changes

2024-08-09 10:40 UTC, merged