Мелкие баги
aaccent/everest-front pull request #33
Opened 2024-08-07 15:16 UTC by regina-ms

- исправлена ошибка в пути `new-building` в шапке в выпадающем меню Новостройки
- в слайдере на главной странице в мобильной версии кнопка **Все** перенесена в контейнер с заголовком 
- добавлен начальный прогресс для слайдера
- добавлен пропс `className` для компонента `<SeeAllCards>`
- добавлены декоративные блоки на детальную страницу ЖК
- переписан компонент `<ObjectList>` с новыми `<Row>` и `<Cell>`

2024-08-09 10:33 UTC, foxhable requested changes
Нужно слегка переделать с целью оптимизации серверных и клиентских компонентов:
1. `Row` сделать клиентским
2. `ObjectsList` сделать серверным, переименовать в `ObjectsTable` и объединить с `LayoutList`
3. Создать компонент-обертку с контекстом и обернуть все таблицы в него. В контексте будет храниться и выводится активный элемент.
4. В `Row` использовать контекст и выставлять активный элемент по клику.

На счёт карточки. Нужно чтобы она была не в одном контейнере с таблицей, а в контейнере со всеми таблицами. Сейчас так:
```jsx
<div>
  <div>
    <Table title="Дом 1" />
    <ObjectCard />
  </div>
  <div>
    <Table title="Дом 2" />
    <ObjectCard />
  </div>
</div>
```

А нужно так:
```jsx
// Ненужные div'ы опущены для упрощения
<div>
  <div>
    <Table title="Дом 1" />
    <Table title="Дом 2" />
  </div>
  <ObjectCard />
</div>
```

Так же сделай карточку `sticky`

2024-08-13 12:44 UTC, foxhable commented on src/components/Carousel/CarouselProgressBar.tsx
> +export function CarouselProgressBar({ className, slides }: Props) {
Через `emblaApi?.slideNodes().length` же вроде можно получить количество слайдов

2024-08-15 15:09 UTC, regina-ms commented on src/components/Carousel/CarouselProgressBar.tsx
> +export function CarouselProgressBar({ className, slides }: Props) {
да можно оказывается

2024-08-19 11:55 UTC, foxhable approved these changes

2024-08-19 11:55 UTC, merged