Попап фильтра и поля
aaccent/everest-front pull request #38
Opened 2024-08-16 14:42 UTC by regina-ms

- Сделаны поля: выпадающий список, поле с бегунком, чекбокс
- Добавлены возможные типы обектов фильтров 
- Начат попап с фильтрами

2024-08-20 06:48 UTC, foxhable requested changes

2024-08-20 06:48 UTC, foxhable commented on src/ui/inputs/Checkbox.tsx
> +  return isInSelect ? (
Зачем нужен `isInSelect`?

2024-08-20 06:48 UTC, foxhable commented on src/types/FiltersType.ts
> +  type: 'radio' | 'multilist' | 'selector-inline' | 'tabs'
`selector-inline` нужно переименовать в `inline-multilist`, т.к это название будет использоваться в апи

2024-08-20 06:59 UTC, regina-ms commented on src/ui/inputs/Range.tsx
> +  /*это временное, позже сделаю компонент, который принимает title и тип инпута*/
Хочу сделать компонент типа FilterItem, который принимает title ('Тип недвижимости', например) и тип инпута(range или selector и тд) и делает нужное поле


Мне казалось это удобным и правильным до того как ты спросил про это

2024-08-20 08:16 UTC, regina-ms commented on src/components/Popup/FilterPopup/FilterPopup.tsx
> +    <div className='relative mt-[64px] h-[1200px] rounded-t-[24px] bg-base-100 md:p-[56px]'>
Это временно было, чтобы проверить что попап скролится

2024-08-20 09:55 UTC, regina-ms commented on src/ui/inputs/Checkbox.tsx
> +  return isInSelect ? (
Очень по разному выглядит чекбокс в селекте и отдельно 
![image](https://github.com/user-attachments/assets/7e98ec6c-5be0-4275-b3eb-33de51076e40)

2024-08-20 09:58 UTC, regina-ms commented on src/ui/inputs/Checkbox.tsx
> +  return isInSelect ? (
По разному выглядят чекбоксы в мобильной версии в зависимости от того в селекте они или самостоятельные 
![image](https://github.com/user-attachments/assets/d09986d8-d6f0-450e-84de-ae4706637926)

2024-08-20 13:47 UTC, regina-ms commented on src/ui/inputs/Range.tsx
> +  /*это временное, позже сделаю компонент, который принимает title и тип инпута*/
пока ничего лучше не придумала и оставила пропс showTitle

2024-08-21 12:16 UTC, foxhable commented on src/ui/inputs/Range.tsx
> +  /*это временное, позже сделаю компонент, который принимает title и тип инпута*/
Идея частично нормальная. Только вместо того чтобы `FilterItem` принимал type, можно сделать чтобы он выводил нужное поле через детей и уже оборачивать им где нужно.

2024-08-21 12:44 UTC, merged