Фильтры
aaccent/everest-front pull request #55
Opened 2024-08-28 14:30 UTC by regina-ms

## Сделано 
- Получение фильтров на страницах категорий - Вторичка и Новостройки 
- Хуки `useCategoryFilter`, `useCategorySort`, `useCategoryObject`

### Нужно понимание как сделать 
- Получение фильтров на страницах подкатегорий, включая ЖК
- Функционал сброса фильтров
- Укороченное значения стоимости в поле `Range`, при этом чтобы в `addFilter` попадало полное значение

2024-09-02 14:16 UTC, foxhable requested changes

2024-09-02 14:16 UTC, foxhable commented on src/page-components/complex/LayoutChoice/LayoutChoice.tsx
> +        {/*/>*/}
Ненужные комментарии убирай. Если думаешь, что это пригодится, то в любой момент можно посмотреть по истории гита

2024-09-02 14:16 UTC, foxhable commented on src/ui/inputs/Radio.tsx
> +    onClick(text)
Можно сократить
```suggestion
    onClick?.(text)
```

2024-09-02 14:38 UTC, regina-ms commented on src/features/price.ts
> +  const _price = typeof price !== 'number' ? safeConvertToPriceNumber(price) : price
действительно, не за чем

2024-09-03 07:38 UTC, foxhable requested changes

2024-09-03 07:38 UTC, foxhable commented on src/layout/catalog/CatalogContent.tsx
> +          )
Так с `ObjectCard` то же самое нужно сделать, что и `ComplexCard`. За шо Карточки объектов обделяешь

2024-09-03 07:38 UTC, foxhable commented on src/features/showFilters.tsx
> +            key={filter.id}
Может вообще не выводить фильтр вместо вывода ненастоящих значений? Иначе смысл в range фильтре, у которого нельзя выбрать значения

```tsx
return filters.map((filter) => {
  if (!filter.value) return null
})
```

2024-09-03 07:38 UTC, foxhable commented on src/globals/api/apiCall.ts
>    return new URLSearchParams(filtered)
Преврати в многострочный код, а то стало тяжело читать:
```suggestion
  const filtered = Object.entries(object).filter(([_, value]) => {
    return value !== undefined && value !== null
  })
```

2024-09-03 07:38 UTC, foxhable commented on src/globals/api/apiCall.ts
>    }
Не, эта проверка вообще не нужна. Нужно убрать блок кода

2024-09-03 09:51 UTC, foxhable approved these changes

2024-09-03 09:51 UTC, merged