Баги 17-09-2024
aaccent/everest-front pull request #77
Opened 2024-09-18 08:10 UTC by regina-ms

## Исправлено 
- https://aaccent.kaiten.ru/space/396039/card/38870401 - переход в галерею при нажатии на послений слайд в галерее карточки 
- https://aaccent.kaiten.ru/space/396039/card/38869355 - подрезала строку названия обьекта чтобы вмещалось красиво
- https://aaccent.kaiten.ru/space/396039/card/38802126 - это в прошлый раз исправляла, в этой ветке тогглы отображаются
- https://aaccent.kaiten.ru/space/396039/card/38799590 - поправила стили в попапе фильтров
- https://aaccent.kaiten.ru/space/396039/card/38791648 - теперь отображается верное кол-во объектов

2024-09-18 11:41 UTC, foxhable commented on src/ui/popups/FilterPopup/ShowAllButton.tsx
> +  return <Button variation='primary' size='small' text={`Показать ${amount} объектов`} className='md:mr-[12px]' />
Добавь чтобы если `amount === 0`, то выводил `null`

2024-09-18 12:02 UTC, regina-ms commented on src/app/catalog/_components/ObjectDetail/ObjectGallery.tsx
> +          activeSlideIndex: list.length - 1,
не помню почему так, щас исправила с учетом новой логики попапов

2024-09-19 07:11 UTC, foxhable commented
> https://aaccent.kaiten.ru/space/396039/card/38952541 - добавила нижний паддниг к футеру на мобилке

Добавь ещё, чтобы зеленая кнопка не налезала на кнопку с футера
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/33b00e3c-920d-4a40-8707-63b702bdd65f)
</details>

2024-09-19 08:03 UTC, foxhable requested changes

2024-09-23 12:44 UTC, foxhable approved these changes

2024-09-23 12:49 UTC, merged